### PR TITLE
Update readme.md: Added HowTo explanation

### PR DESCRIPTION
**Pull request by s-a-s-k-i-a**
Let's make it noobfriendlier. ;)

Inspired by @La-Geek @Lageek latest comments

### CODE REVIEW

**Comment by 2ndkauboy** [comment]
Thanks! This is how collabortaion should always be :) There are some typos in your text (e.g. German has to beacapitalized). Do you want to correct them? If not, I can do it after merging your changes in.

**Comment by s-a-s-k-i-a** [comment]
Corrected the capitalization. Hope there are no other typos in my text. I doublechecked my text once more, however I can't see anything else... 

Would be nice if you could change any typos that slipped through.

**Comment by 2ndkauboy** [comment]
Great. It would be nice, if you could rebase your commits into a single commit, if you know how to do that if not, that's fine. I will merge it anyways tomorrow and maybe change some of my paragaphs.

**Comment by s-a-s-k-i-a** [comment]
The #14057dd should be the squashed commit :) 
Never done this before.. hope its ok

**Comment by 2ndkauboy** [comment]
Not quite :)

How do you use Git? Using the Terminal/Console or through a GUI?

If you use the terminal, here is how to do it:

Before you start, you should define a decent text editor, as otherwise, VIM would be used. Run one of the following commands, depending on the OS/Editor you use:

`git config --global core.editor "'C:/Program Files/Notepad++/notepad++.exe' -multiInst -nosession -noPlugin"` (Windows x86)
`git config --global core.editor "'C:/Program Files (x86)/Notepad++/notepad++.exe' -multiInst -notabbar -nosession -noPlugin"` (Windows x64)
`git config --global core.editor "mate -w"` (Mac OS X Textmate Editor)
`git config --global core.editor "subl -n -w"` (Mac OS X Sublime Text)
`git config --global core.editor open` (Mac OS X Editor)

Than you can do the rebase:

`git chekcout master` (if you are on another branch)
`git rebase -i 0bc62d8` (`0bc62d8` is the commit, you merge off)

Then a editor will open. Change the word `pick` to `s` for all, but the first commit. Than save the opened text file. The commits will than be squashed into a single commit.

You then have to perform a "force push", to update your pull-request:
`git push -f`

Here you can find a quick guide on how to use interactive rebases when contributing to a project: http://www.mongodb.org/about/contributors/tutorial/submit-a-github-pull-request/

**Comment by 2ndkauboy** [comment]
I have merged in your changes manually. Sorry for the hugh delay in applying the changes. And thanks again for your help!

**Pull request closed without merging**
